const DB_NAME='ledger-db', STORE='expenses', SETTINGS='settings';
let db, expenses=[], selectedMonth=new Date().toISOString().slice(0,7), attachedFile=null, settings={baseCurrency:'EUR',usdRate:1.08,months:[selectedMonth]};
const $=id=>document.getElementById(id), money=(n,c='USD')=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(Number(n)||0);
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'});if(!d.objectStoreNames.contains(SETTINGS))d.createObjectStore(SETTINGS,{keyPath:'key'})};req.onsuccess=()=>{db=req.result;resolve(db)};req.onerror=()=>reject(req.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function getAll(store){return new Promise(r=>{const q=tx(store).getAll();q.onsuccess=()=>r(q.result)})}
function put(store,val){return new Promise(r=>{const q=tx(store,'readwrite').put(val);q.onsuccess=()=>r()})}
function remove(store,key){return new Promise(r=>{const q=tx(store,'readwrite').delete(key);q.onsuccess=()=>r()})}
function monthLabel(m){return new Intl.DateTimeFormat('es-ES',{month:'long',year:'numeric'}).format(new Date(`${m}-01`)).replace(/^./,x=>x.toUpperCase())}
function idForMonth(){const n=expenses.filter(x=>x.id.startsWith(selectedMonth)).length+1;return `${selectedMonth}-${String(n).padStart(3,'0')}`}
function filtered(){const s=($('search-input')?.value||'').toLowerCase(),c=$('category-filter')?.value||'',st=$('status-filter')?.value||'';return expenses.filter(x=>x.date.startsWith(selectedMonth)&&(!s||`${x.id} ${x.merchant}`.toLowerCase().includes(s))&&(!c||x.category===c)&&(!st||x.status===st)).sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id))}
function render(){const rows=filtered(), allMonth=expenses.filter(x=>x.date.startsWith(selectedMonth)), pending=allMonth.filter(x=>x.status==='review');$('month-name').textContent=monthLabel(selectedMonth);$('today-label').textContent=monthLabel(selectedMonth).toUpperCase();$('nav-count').textContent=allMonth.length;$('review-count').textContent=pending.length;$('metric-review').textContent=pending.length;$('metric-files').textContent=allMonth.filter(x=>x.fileName).length;$('metric-total').textContent=money(allMonth.reduce((s,x)=>s+x.usdTotal,0),'USD');$('metric-original').textContent=`${allMonth.length} gasto${allMonth.length===1?'':'s'} registrado${allMonth.length===1?'':'s'}`;$('table-count').textContent=`${rows.length} registro${rows.length===1?'':'s'}`;$('month-list').innerHTML=(settings.months||[]).sort().reverse().map(m=>`<button class="month-card ${m===selectedMonth?'selected':''}" data-select-month="${m}"><span><strong>${monthLabel(m)}</strong><small>${expenses.filter(x=>x.date.startsWith(m)).length} gastos</small></span><span class="month-arrow">→</span></button>`).join('');
  $('recent-list').innerHTML=allMonth.slice().sort((a,b)=>b.createdAt-a.createdAt).slice(0,5).map(itemHTML).join('')||'<div class="empty-state">Todavía no hay gastos este mes.<br>Captura tu primer comprobante.</div>';
  $('expense-table').innerHTML=rows.map(x=>`<tr><td>${x.id}</td><td><strong>${esc(x.merchant||'Sin comercio')}</strong></td><td>${x.date}</td><td>${x.category}</td><td>${money(x.amount,x.currency)}</td><td><strong>${money(x.usdTotal,'USD')}</strong></td><td><span class="status ${x.status}">${x.status==='review'?'◌ Por revisar':'● Confirmado'}</span></td><td><button class="row-action" data-edit="${x.id}" aria-label="Editar ${x.id}">···</button></td></tr>`).join('')||'<tr><td colspan="8"><div class="empty-state">No hay registros que coincidan.</div></td></tr>';
  $('review-list').innerHTML=pending.map(x=>`<article class="review-card"><div class="expense-avatar">${initials(x.merchant)}</div><div class="review-copy"><h3>${esc(x.merchant||'Comprobante sin identificar')}</h3><p>${x.id} · ${x.fileName||'sin archivo'} · Revisa comercio y total antes de confirmar.</p></div><button class="button primary" data-confirm="${x.id}">Revisar ahora</button></article>`).join('')||'<div class="panel empty-state">Todo en orden. No hay comprobantes pendientes.</div>';
}
function itemHTML(x){return `<div class="expense-item"><div class="expense-avatar">${initials(x.merchant)}</div><div class="expense-main"><strong>${esc(x.merchant||'Sin comercio')}</strong><span>${x.id} · ${x.category}</span></div><div class="expense-amount">${money(x.usdTotal,'USD')}<small>${x.status==='review'?'Por revisar':x.date}</small></div></div>`}
function initials(s){return (s||'??').split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;',"\"":'&quot;'}[c]))}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));$(`${name}-view`).classList.add('active-view');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$('page-title').textContent={overview:'Resumen',months:'Meses',expenses:'Gastos',review:'Revisar',settings:'Configuración'}[name]}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function updateConversion(){const a=Number($('amount').value)||0,r=Number($('exchange-rate').value)||0;$('conversion-total').textContent=money(a*r,'USD')+' USD'}
async function fileToData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
async function processFile(file){attachedFile=file;$('drop-zone').classList.add('hidden');$('ocr-status').classList.remove('hidden');$('capture-fields').classList.remove('hidden');$('expense-date').value=new Date().toISOString().slice(0,10);$('merchant').value=file.name.replace(/\.[^.]+$/,'').replace(/[-_]/g,' ')||'';$('amount').value='';$('merchant').focus();if(!file.type.startsWith('image/')||!window.Tesseract){$('ocr-status').textContent=`${file.name} listo. El OCR está disponible para imágenes; confirma los datos antes de guardar.`;return}try{$('ocr-status').textContent='OCR local en curso… la imagen no sale de tu navegador.';const result=await Tesseract.recognize(file,'spa+eng',{logger:m=>{if(m.status==='recognizing text')$('ocr-status').textContent=`OCR local en curso… ${Math.round((m.progress||0)*100)}%`}});const text=result.data.text.trim();const lines=text.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(lines[0])$('merchant').value=lines[0].slice(0,80);const amounts=[...text.matchAll(/(?:total|importe|amount)\s*[:]?\s*([0-9]+[.,][0-9]{2})/ig)].map(m=>Number(m[1].replace(',','.')));if(amounts[0])$('amount').value=amounts[0].toFixed(2);$('ocr-status').textContent=text?`OCR completado. ${amounts.length?'Total detectado; revisa los campos antes de guardar.':'Revisa el comercio y el total detectado.'}`:'No se pudo leer texto con seguridad; completa los campos manualmente.';updateConversion()}catch(err){$('ocr-status').textContent='No se pudo completar el OCR. Puedes completar los datos manualmente.';console.warn(err)}}
function openCapture(){if(!(settings.months||[]).includes(selectedMonth)){showView('months');toast('Crea o selecciona un mes antes de añadir gastos');return}attachedFile=null;$('capture-dialog').showModal();$('drop-zone').classList.remove('hidden');$('capture-fields').classList.add('hidden');$('ocr-status').classList.add('hidden');$('capture-form').reset();$('exchange-rate').value=settings.usdRate;$('currency').value=settings.baseCurrency;}
async function saveExpense(){const amount=Number($('amount').value), rate=Number($('exchange-rate').value)||1;if(!amount)return;const id=idForMonth(),file=attachedFile?{fileName:`${id}.${attachedFile.name.split('.').pop()}`,fileData:await fileToData(attachedFile)}:{};const e={id,merchant:$('merchant').value.trim()||'Sin comercio',date:$('expense-date').value||new Date().toISOString().slice(0,10),category:$('category').value,amount,currency:$('currency').value,exchangeRate:rate,baseCurrency:settings.baseCurrency,usdTotal:$('currency').value==='USD'?amount:amount*rate,notes:$('notes').value,status:'review',createdAt:Date.now(),...file};await put(STORE,e);expenses.push(e);$('capture-dialog').close();render();toast(`${id} guardado en revisión`)}
function exportProject(){const payload={version:1,exportedAt:new Date().toISOString(),settings,expenses};download(JSON.stringify(payload),'ledger-project.ledger','application/json')}
function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function excel(){const rows=filtered();const escxml=s=>esc(s).replace(/\n/g,' ');const sheet=(name,headers,data)=>`<Worksheet ss:Name="${name}"><Table><Row>${headers.map(h=>`<Cell><Data ss:Type="String">${h}</Data></Cell>`).join('')}</Row>${data.map(row=>`<Row>${row.map(v=>`<Cell><Data ss:Type="String">${escxml(v)}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet>`;const cats=[...new Set(rows.map(x=>x.category))].map(c=>[c,rows.filter(x=>x.category===c).reduce((s,x)=>s+x.usdTotal,0).toFixed(2)]);const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Resumen"><Table><Row><Cell><Data ss:Type="String">Mes</Data></Cell><Cell><Data ss:Type="String">${monthLabel(selectedMonth)}</Data></Cell></Row><Row><Cell><Data ss:Type="String">Total USD</Data></Cell><Cell><Data ss:Type="Number">${rows.reduce((s,x)=>s+x.usdTotal,0).toFixed(2)}</Data></Cell></Row></Table></Worksheet>${sheet('Gastos',['ID','Comercio','Fecha','Categoría','Importe','Moneda','Tipo de cambio','Total USD','Estado','Comprobante'],rows.map(x=>[x.id,x.merchant,x.date,x.category,x.amount,x.currency,x.exchangeRate,x.usdTotal.toFixed(2),x.status,x.fileName||'']))}${sheet('Categorías',['Categoría','Total USD'],cats)}</Workbook>`;download(xml,`ledger-${selectedMonth}.xls`,'application/vnd.ms-excel');toast('Excel mensual exportado')}
async function importProject(file){const data=JSON.parse(await file.text());settings=data.settings||settings;for(const x of data.expenses||[])await put(STORE,x);expenses=await getAll(STORE);applySettings();render();toast('Proyecto importado correctamente')}
function applySettings(){$('base-currency').value=settings.baseCurrency;$('usd-rate').value=settings.usdRate}
document.addEventListener('click',async e=>{const nav=e.target.closest('[data-view]');if(nav)showView(nav.dataset.view);if(e.target.closest('#open-capture')||e.target.closest('#open-capture-2'))openCapture();if(e.target.id==='export-excel')excel();if(e.target.id==='export-project')exportProject();if(e.target.id==='import-project')$('project-file').click();if(e.target.dataset.confirm){const x=expenses.find(v=>v.id===e.target.dataset.confirm);if(x){x.status='confirmed';await put(STORE,x);render();toast(`${x.id} confirmado`)}}if(e.target.dataset.edit){const x=expenses.find(v=>v.id===e.target.dataset.edit);if(x){showView('review');const ok=confirm(`¿Confirmar ${x.id} (${x.merchant})?`);if(ok){x.status='confirmed';await put(STORE,x);render();toast('Gasto confirmado')}}}});
['search-input','category-filter','status-filter'].forEach(id=>$(id).addEventListener('input',render));$('prev-month').onclick=()=>{const d=new Date(`${selectedMonth}-01`);d.setMonth(d.getMonth()-1);selectedMonth=d.toISOString().slice(0,7);render()};$('next-month').onclick=()=>{const d=new Date(`${selectedMonth}-01`);d.setMonth(d.getMonth()+1);selectedMonth=d.toISOString().slice(0,7);render()};$('file-input').onchange=e=>e.target.files[0]&&processFile(e.target.files[0]);$('camera-input').onchange=e=>e.target.files[0]&&processFile(e.target.files[0]);['amount','exchange-rate'].forEach(id=>$(id).addEventListener('input',updateConversion));$('capture-form').addEventListener('submit',e=>{e.preventDefault();saveExpense()});$('drop-zone').addEventListener('dragover',e=>{e.preventDefault();$('drop-zone').classList.add('dragging')});$('drop-zone').addEventListener('dragleave',()=>$('drop-zone').classList.remove('dragging'));$('drop-zone').addEventListener('drop',e=>{e.preventDefault();$('drop-zone').classList.remove('dragging');if(e.dataTransfer.files[0])processFile(e.dataTransfer.files[0])});$('base-currency').onchange=async e=>{settings.baseCurrency=e.target.value;await put(SETTINGS,{key:'config',...settings});toast('Moneda base actualizada')};$('usd-rate').onchange=async e=>{settings.usdRate=Number(e.target.value)||1;await put(SETTINGS,{key:'config',...settings});toast('Tipo de cambio actualizado')};$('project-file').onchange=e=>e.target.files[0]&&importProject(e.target.files[0]);
(async()=>{await openDB();expenses=await getAll(STORE);const cfg=await getAll(SETTINGS);if(cfg[0])settings={baseCurrency:cfg[0].baseCurrency||'EUR',usdRate:cfg[0].usdRate||1.08,months:cfg[0].months||[selectedMonth]};if(!settings.months.includes(selectedMonth)&&!expenses.length){settings.months.push(selectedMonth);await put(SETTINGS,{key:'config',...settings})}applySettings();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js')})().catch(console.error);

document.addEventListener('click',async e=>{if(e.target.id==='quick-camera'){openCapture();setTimeout(()=>$('camera-input').click(),80)}if(e.target.id==='quick-upload'){openCapture();setTimeout(()=>$('file-input').click(),80)}if(e.target.dataset.selectMonth){selectedMonth=e.target.dataset.selectMonth;render();showView('overview');toast(`Mes activo: ${monthLabel(selectedMonth)}`)}if(e.target.id==='create-month'){const m=$('new-month').value;if(!m){toast('Elige un mes antes de continuar');return}if(!settings.months.includes(m)){settings.months.push(m);await put(SETTINGS,{key:'config',...settings});selectedMonth=m;render();toast(`${monthLabel(m)} creado`)}else{selectedMonth=m;render();showView('overview');toast('Ese mes ya existe')}}});

const supportedCurrencies=[['USD','Dólar estadounidense'],['MXN','Peso mexicano'],['COP','Peso colombiano'],['ARS','Peso argentino'],['UYU','Peso uruguayo'],['BRL','Real brasileño'],['CLP','Peso chileno'],['PEN','Sol peruano'],['BOB','Boliviano'],['PYG','Guaraní paraguayo'],['VES','Bolívar venezolano']];function applyCurrencyList(){['currency','base-currency'].forEach(id=>{const el=$(id);if(!el)return;const current=el.value;el.innerHTML=supportedCurrencies.map(([code,name])=>`<option value="${code}">${code} — ${name}</option>`).join('');el.value=supportedCurrencies.some(x=>x[0]===current)?current:'USD'})}applyCurrencyList();

(function(){const w=document.createElement('section');w.id='welcome';w.innerHTML='<div class="welcome-inner"><div class="welcome-brand"><span class="brand-mark">🔥</span><span>fire flow</span></div><span class="section-kicker">CONTABILIDAD PERSONAL · LOCAL-FIRST</span><h2>Tu dinero,<br><em>bajo control.</em></h2><p>Captura tickets, revisa los datos y cierra cada mes con claridad. Tus comprobantes y tus números permanecen en este dispositivo.</p><div><button class="button primary" id="welcome-start">Crear mi primer mes ↗</button><button class="text-button" id="welcome-skip">Entrar directamente</button></div><small>Sin cuentas · Sin nube · Tus datos son tuyos</small></div>';const css=document.createElement('style');css.textContent='#welcome{position:fixed;inset:0;z-index:50;background:#fafafa;display:grid;place-items:center;text-align:center;padding:28px}#welcome .welcome-inner{max-width:620px}#welcome .welcome-brand{display:flex;justify-content:center;align-items:center;gap:9px;font-size:19px;font-weight:700;margin-bottom:70px}#welcome h2{font-size:clamp(48px,8vw,82px);line-height:.92;letter-spacing:-.09em;margin:18px 0 22px}#welcome em{font-style:normal;color:#102a56}#welcome p{max-width:460px;color:#71717a;font-size:15px;line-height:1.6;margin:0 auto 28px}#welcome .text-button{margin-left:15px}#welcome small{display:block;color:#aaa;font-size:11px;margin-top:22px}';document.head.appendChild(css);document.body.prepend(w);$('welcome-start').onclick=()=>w.remove();$('welcome-skip').onclick=()=>w.remove()})();

(function(){const a=document.createElement('a');a.href='https://hernansuy.github.io/Fire-Flow/';a.target='_blank';a.rel='noopener';a.textContent='Probar demo online ↗';a.style='display:block;margin-top:18px;color:#102a56;font:600 13px Geist,Arial,sans-serif;text-decoration:none';const actions=document.querySelector('#welcome .welcome-inner > div:last-of-type');if(actions)actions.appendChild(a)})();

import('./paddle-ocr.js').catch(() => {});
